#on:
#  push:
#    tags:
#      - '*.*.*'

on:
  schedule:
    # Midnight
    - cron: "9 15 * * *"


name: Systemd update

jobs:
  update:
    name: Systemd update job
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    steps:
      - name: Run cron
        run: |
           curl -X 'POST' \
               'https://api.opensuse.org/trigger/runservice?project=home:dspinella:systemd&package=systemd' \
               -H 'accept: application/xml; charset=utf-8' \
               -H "X-GitLab-Token: $TOKEN" \
               -H 'X-GitLab-Event: commit' \
               -d ''
